[package]
name = "neo-auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
jsonwebtoken = "9.3.0"
serde = { version = "1.0", features = ["derive"] }
