[package]
name = "neo-dao-service"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.210"
futures = "0.3.30"
tokio = {version = "1.40.0", features = ["full"]}
urlencoding = "2.1.3"

[dependencies.mongodb]
version = "3.1.0"

[dev-dependencies]
dotenv = "0.15.0"
