[package]
name = "neo-ms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4.9.0"
derive_more = { version = "1.0.0", features = ["display", "error"] }
envy = "0.4.2"
futures-util = "0.3.30"
log = { version = "0.4.22", features = ["kv"] }
neo-auth-service = { path = "../neo-auth-service" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
uuid = { version = "1.10.0", features = ["v4"] }
